<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class UsersTableSeeder extends Seeder {
	/**
	* Run the database seeds.
	*
	* @return void
	*/
	public function run() {
		DB::table('users')->insert([
			'username'=>'talek',
			'password'=>$this->generatesPassword('9kg]Hdmu,'),
			'titleName'=>'Mr',
			'firstName'=>'talek',
			'lastname'=>'team',
			'idcard'=>'1234567891234',
			'email'=>'talek@team.com',
			'ref_position'=>1,
			'ref_office'=>1,
			'user_type'=>'root',
			'avatar'=>'default-avatar.png',
			'register'=>Carbon::now(),
			'created_at'=>Carbon::now()
		]);
		DB::table('users')->insert([
			'username'=>'junjila',
			'password'=>$this->generatesPassword('hinjumpa39'),
			'titleName'=>'นางสาว',
			'firstName'=>'จุลจิลา',
			'lastname'=>'หินจำปา',
			'idcard'=>'1234567891234',
			'email'=>'junjila@ucdd.com',
			'ref_position'=>1,
			'ref_office'=>1,
			'user_type'=>'administrator',
			'avatar'=>'default-avatar.png',
			'register'=>Carbon::now(),
			'created_at'=>Carbon::now()
		]);
		DB::table('users')->insert([
			'username'=>'iudc',
			'password'=>$this->generatesPassword('456789'),
			'titleName'=>null,
			'firstName'=>'IUDC',
			'lastname'=>'สปคม.',
			'idcard'=>'1234567891234',
			'email'=>'iudc@ucdd.com',
			'ref_position'=>null,
			'ref_office'=>1,
			'user_type'=>'administrator',
			'avatar'=>'default-avatar.png',
			'register'=>Carbon::now(),
			'created_at'=>Carbon::now()
		]);
		DB::table('users')->insert([
			'username'=>'dpc001',
			'password'=>$this->generatesPassword('123456'),
			'titleName'=>null,
			'firstName'=>'DPC001',
			'lastname'=>'สคร.',
			'idcard'=>'1234567891234',
			'email'=>'dpc001@ucdd.com',
			'ref_position'=>1,
			'ref_office'=>2,
			'user_type'=>'viewer',
			'avatar'=>'default-avatar.png',
			'register'=>Carbon::now(),
			'created_at'=>Carbon::now()
		]);
		DB::table('users')->insert([
			'username'=>'dpc002',
			'password'=>$this->generatesPassword('123456'),
			'titleName'=>null,
			'firstName'=>'DPC002',
			'lastname'=>'สคร.',
			'idcard'=>'1234567891234',
			'email'=>'dpc002@ucdd.com',
			'ref_position'=>1,
			'ref_office'=>2,
			'user_type'=>'viewer',
			'avatar'=>'default-avatar.png',
			'register'=>Carbon::now(),
			'created_at'=>Carbon::now()
		]);
		DB::table('users')->insert([
			'username'=>'dpc003',
			'password'=>$this->generatesPassword('123456'),
			'titleName'=>null,
			'firstName'=>'DPC003',
			'lastname'=>'สคร.',
			'idcard'=>'1234567891234',
			'email'=>'dpc003@ucdd.com',
			'ref_position'=>1,
			'ref_office'=>2,
			'user_type'=>'viewer',
			'avatar'=>'default-avatar.png',
			'register'=>Carbon::now(),
			'created_at'=>Carbon::now()
		]);
		DB::table('users')->insert([
			'username'=>'dpc004',
			'password'=>$this->generatesPassword('123456'),
			'titleName'=>null,
			'firstName'=>'DPC004',
			'lastname'=>'สคร.',
			'idcard'=>'1234567891234',
			'email'=>'dpc004@ucdd.com',
			'ref_position'=>1,
			'ref_office'=>2,
			'user_type'=>'viewer',
			'avatar'=>'default-avatar.png',
			'register'=>Carbon::now(),
			'created_at'=>Carbon::now()
		]);
		DB::table('users')->insert([
			'username'=>'dpc005',
			'password'=>$this->generatesPassword('123456'),
			'titleName'=>null,
			'firstName'=>'DPC005',
			'lastname'=>'สคร.',
			'idcard'=>'1234567891234',
			'email'=>'dpc005@ucdd.com',
			'ref_position'=>1,
			'ref_office'=>2,
			'user_type'=>'viewer',
			'avatar'=>'default-avatar.png',
			'register'=>Carbon::now(),
			'created_at'=>Carbon::now()
		]);
		DB::table('users')->insert([
			'username'=>'dpc006',
			'password'=>$this->generatesPassword('123456'),
			'titleName'=>null,
			'firstName'=>'DPC006',
			'lastname'=>'สคร.',
			'idcard'=>'1234567891234',
			'email'=>'dpc006@ucdd.com',
			'ref_position'=>1,
			'ref_office'=>2,
			'user_type'=>'viewer',
			'avatar'=>'default-avatar.png',
			'register'=>Carbon::now(),
			'created_at'=>Carbon::now()
		]);
		DB::table('users')->insert([
			'username'=>'dpc007',
			'password'=>$this->generatesPassword('123456'),
			'titleName'=>null,
			'firstName'=>'DPC007',
			'lastname'=>'สคร.',
			'idcard'=>'1234567891234',
			'email'=>'dpc007@ucdd.com',
			'ref_position'=>1,
			'ref_office'=>2,
			'user_type'=>'viewer',
			'avatar'=>'default-avatar.png',
			'register'=>Carbon::now(),
			'created_at'=>Carbon::now()
		]);
		DB::table('users')->insert([
			'username'=>'dpc008',
			'password'=>$this->generatesPassword('123456'),
			'titleName'=>null,
			'firstName'=>'DPC008',
			'lastname'=>'สคร.',
			'idcard'=>'1234567891234',
			'email'=>'dpc008@ucdd.com',
			'ref_position'=>1,
			'ref_office'=>2,
			'user_type'=>'viewer',
			'avatar'=>'default-avatar.png',
			'register'=>Carbon::now(),
			'created_at'=>Carbon::now()
		]);
		DB::table('users')->insert([
			'username'=>'dpc009',
			'password'=>$this->generatesPassword('123456'),
			'titleName'=>null,
			'firstName'=>'DPC009',
			'lastname'=>'สคร.',
			'idcard'=>'1234567891234',
			'email'=>'dpc009@ucdd.com',
			'ref_position'=>1,
			'ref_office'=>2,
			'user_type'=>'viewer',
			'avatar'=>'default-avatar.png',
			'register'=>Carbon::now(),
			'created_at'=>Carbon::now()
		]);
		DB::table('users')->insert([
			'username'=>'dpc010',
			'password'=>$this->generatesPassword('123456'),
			'titleName'=>null,
			'firstName'=>'DPC010',
			'lastname'=>'สคร.',
			'idcard'=>'1234567891234',
			'email'=>'dpc010@ucdd.com',
			'ref_position'=>1,
			'ref_office'=>2,
			'user_type'=>'viewer',
			'avatar'=>'default-avatar.png',
			'register'=>Carbon::now(),
			'created_at'=>Carbon::now()
		]);
		DB::table('users')->insert([
			'username'=>'dpc011',
			'password'=>$this->generatesPassword('123456'),
			'titleName'=>null,
			'firstName'=>'DPC011',
			'lastname'=>'สคร.',
			'idcard'=>'1234567891234',
			'email'=>'dpc011@ucdd.com',
			'ref_position'=>1,
			'ref_office'=>2,
			'user_type'=>'viewer',
			'avatar'=>'default-avatar.png',
			'register'=>Carbon::now(),
			'created_at'=>Carbon::now()
		]);
		/* position tbl seed */
		DB::table('position')->insert([
			'pos_name'=>'นักวิชาการสาธารณสุข',
			'pos_name_en'=>'Public health scholar'
		]);
		/* office tbl seed */
		DB::table('office')->insert([
			'off_name_full'=>'สถาบันป้องกันโรคควบคุมโรคเขตเมือง',
			'off_name_short'=>'สปคม.',
			'off_name_en'=>'Institute for Urban Disease Control and Prevention'
		]);
		DB::table('office')->insert([
			'off_name_full'=>'สำนักงานป้องกันโรคควบคุมโรค',
			'off_name_short'=>'สคร.',
			'off_name_en'=>'Office of Disease Prevention and Control'
		]);
		DB::table('office')->insert([
			'off_name_full'=>'สำนักระบาดวิทยา',
			'off_name_short'=>'สนร.',
			'off_name_en'=>'Bureau Of Epidemiology'
		]);
	}

	protected function generatesPassword($password='test') {
		return bcrypt($password);
	}
}
